
package ru.iuribabalin.app;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceImpl", targetNamespace = "http://app.iuribabalin.ru/")
@XmlSeeAlso({
    ru.iuribabalin.app.ObjectFactory.class,
    ru.iuribabalin.app.model.ObjectFactory.class
})
public interface EmployeeServiceImpl {


    /**
     * 
     * @param firstName
     * @param lastName
     * @param data
     * @param position
     * @param department
     * @return
     *     returns ru.iuribabalin.app.EmployeeSearchResponseType
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(name = "EmployeeSearchResponse", targetNamespace = "http://app.iuribabalin.ru/")
    @RequestWrapper(localName = "searchEmployees", targetNamespace = "http://app.iuribabalin.ru/", className = "ru.iuribabalin.app.SearchEmployees")
    @ResponseWrapper(localName = "searchEmployeesResponse", targetNamespace = "http://app.iuribabalin.ru/", className = "ru.iuribabalin.app.SearchEmployeesResponse")
    @Action(input = "http://app.iuribabalin.ru/EmployeeServiceImpl/searchEmployeesRequest", output = "http://app.iuribabalin.ru/EmployeeServiceImpl/searchEmployeesResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://app.iuribabalin.ru/EmployeeServiceImpl/searchEmployees/Fault/ParseException")
    })
    public EmployeeSearchResponseType searchEmployees(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "position", targetNamespace = "")
        Position position,
        @WebParam(name = "department", targetNamespace = "")
        Department department,
        @WebParam(name = "data", targetNamespace = "")
        String data)
        throws ParseException_Exception
    ;

}
